server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///home/ubuntu/microservice-architecture/config-repo
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
