spring:
  application:
    name: sensor-service
  datasource:
    url: jdbc:h2:mem:testdb-sensor-service-2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  config:
    import: optional:configserver:http://localhost:8888
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

application:
  security:
    jwt:
      secret-key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
      expiration: 3600000 # Token validity duration in milliseconds (e.g., 1 hour)

